const recepty = [
  { nadpis: 'Prosciutto',
    popis: 'Prosciutto Cotto, fior di latte mozzarella, extra panenský olivový olej, rajčata San Marzano ',
    hodnoceni: 4.9,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Prosciutto.png'
  },
  { nadpis: 'Quattro formaggi',
    popis: 'Taleggio sýr z Lombardie, fior di latte mozzarella, Gorngozola Dolce , Grana Padano, rukola, smetana',
    hodnoceni: 1.8,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Quattro.png'
  },
  { nadpis: 'Bomba',
    popis: 'Prosciutto Cotto, italská slanina pancetta, žampiony, Gorgonzola, fior di latte mozzarella, cibule tropea, rajčata San Marzano',
    hodnoceni: 3.9,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Bomba.png'
  },
  { nadpis: 'Capricciosa',
    popis: 'Prosciutto Cotto, fior di latte mozzarella, žampiony, olivy, artyčoky, extra panenský olivový olej, rajčata San Marzano',
    hodnoceni: 4.5,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Capricciosa.png'
  },
  { nadpis: 'Mexicana',
    popis: 'Italská klobása Napoli, taleggio sýr z Lombardie, cheddar, feferonky, kukuřice, cibule tropea, fior di latte mozzarella, rajčata San Marzano ',
    hodnoceni: 3.5,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Mexicana.png'
  },
  { nadpis: 'Štrůdl Pizza',
    popis: ' Jablka Golden, rozinky, skořice, smetana ',
    hodnoceni: 1.5,
    kategorie: 'Sladká pizza',
    stitek: 'sladkaPizza',
    img: 'images/Strudl.png'
  },
  { nadpis: 'Borůvková pizza',
    popis: ' Borůvky, smetana, drobenka ',
    hodnoceni: 5,
    kategorie: 'Sladká pizza',
    stitek: 'sladkaPizza',
    img: 'images/Boruvkova.png'
  },
  { nadpis: 'Jahodova pizza',
    popis: 'Jahody, lučina, bazalka a třtinový cukr',
    hodnoceni: 2.9,
    kategorie: 'Sladká pizza',
    stitek: 'sladkaPizza',
    img: 'images/Jahodova.png'
  },
  { nadpis: 'Choco Pizza',
    popis: 'Parmazán, balsamico, hořká čokoláda, máslo',
    hodnoceni: 4.6,
    kategorie: 'Sladká pizza',
    stitek: 'sladkaPizza',
    img: 'images/ChocoPizza.png'
  },
  { nadpis: 'Melanzane',
    popis: 'Smetana, lilek, italská slanina pancetta, fior di latte mozzarella, extra panenský olivový olej ',
    hodnoceni: 3.8,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Melanzane.png'
  },
  { nadpis: 'Frutti di Mare',
    popis: 'Morské plody, mozzarella Fior di latte, extra panenský olivový olej, rajčata San Marzano.',
    hodnoceni: 4.1,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/FurriDiMare.png'
  },
  { nadpis: 'Lanýžová pizza',
    popis: 'Vepřová klobása Salsiccia z Toskánska, fior di latte mozzarella, salsa di tartufo, žampiony, smetana a ricotta.',
    hodnoceni: 1.8,
    kategorie: 'Slaná pizza',
    stitek: 'slanaPizza',
    img: 'images/Lanyzova.png'
  },
  { nadpis: 'Bezlepková pizza',
    popis: 'Prosciutto, Mozarrela, Sugo, Parmazán, Rukola, Polníček, Oregano.',
    hodnoceni: 4.9,
    kategorie: 'Speciální pizza',
    stitek: 'specialni',
    img: 'images/Bezlepkova.png'
  },
  { nadpis: 'Bostoncini',
    popis: 'Tyčinky - česnekový olej, uzený sýr, mozzarella, pepř.',
    hodnoceni: 4.2,
    kategorie: 'Speciální pizza',
    stitek: 'specialni',
    img: 'images/Tycinky.png'
  },
  { nadpis: 'Calzone',
    popis: 'Prřekládaná pizza - ricotta, chedar, paprika, feferonky, guanciale, rajřata, chilli',
    hodnoceni: 4.7,
    kategorie: 'Speciální pizza',
    stitek: 'specialni',
    img: 'images/Calzone.png'
  },
  { nadpis: 'Pizza Naháč',
    popis: 'Pizza bez těsta/korpusu, takže vlastně salát - rajčata, mozarrela, parmazán, artyčoky, vejce, polníček',
    hodnoceni: 5,
    kategorie: 'Speciální pizza',
    stitek: 'Speciální pizza',
    img: 'images/Nahac.png'
  },
]
